// EntityAttack.cs
// 
// Author: Max Jackman
// Email:  max.jackman@outlook.com
// Date:   November 19, 2023

using UnityEngine;

namespace Zop
{
	/// <summary>
	/// An attack generated by a weapon entity.
	/// </summary>
	public class EntityAttack : MonoBehaviour, IAttack
	{
		public IAttack InternalAttack { get { return _attack; } set { _attack = value; } }

		public IWeapon Weapon => _attack.Weapon;
		public float Damage => _attack.Damage;

		public ulong SenderID => _attack.SenderID;
		public ulong[] TargetIDs => _attack.TargetIDs;
		public Vector3 Origin => _attack.Origin;
		public Vector3 Destination => _attack.Destination;

		private IAttack _attack;
	}
}